-- MySQL Script generated by MySQL Workbench
-- Mon Nov 28 22:13:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UniViewUsers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UniViewUsers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UniViewUsers` DEFAULT CHARACTER SET utf8 ;
USE `UniViewUsers` ;

-- -----------------------------------------------------
-- Table `UniViewUsers`.`StData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniViewUsers`.`StData` (
  `idStData` INT NOT NULL,
  `stSchoolType` VARCHAR(45) NULL,
  `StCity` VARCHAR(45) NULL,
  `StSchoolPref` VARCHAR(45) NULL,
  PRIMARY KEY (`idStData`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniViewUsers`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniViewUsers`.`Students` (
  `idStudents` INT NOT NULL,
  `studentUsername` VARCHAR(45) NOT NULL,
  `studentPassword` VARCHAR(45) NOT NULL,
  `stPreferences` INT NULL,
  PRIMARY KEY (`idStudents`),
  UNIQUE INDEX `idStudents_UNIQUE` (`idStudents` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`studentUsername` ASC) VISIBLE,
  INDEX `idStData_idx` (`stPreferences` ASC) VISIBLE,
  CONSTRAINT `theStData`
    FOREIGN KEY (`stPreferences`)
    REFERENCES `UniViewUsers`.`StData` (`idStData`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniViewUsers`.`teData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniViewUsers`.`teData` (
  `idTeData` INT NOT NULL,
  `teCity` VARCHAR(45) NULL,
  `teSchoolPref` VARCHAR(45) NULL,
  PRIMARY KEY (`idTeData`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniViewUsers`.`Teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniViewUsers`.`Teachers` (
  `idTeachers` INT NOT NULL AUTO_INCREMENT,
  `teacherUsername` VARCHAR(45) NOT NULL,
  `teacherPassword` VARCHAR(45) NOT NULL,
  `teacherPreference` INT NULL,
  PRIMARY KEY (`idTeachers`),
  UNIQUE INDEX `idTeachers_UNIQUE` (`idTeachers` ASC) VISIBLE,
  UNIQUE INDEX `teacherUsername_UNIQUE` (`teacherUsername` ASC) VISIBLE,
  INDEX `theTeData_idx` (`teacherPreference` ASC) VISIBLE,
  CONSTRAINT `theTeData`
    FOREIGN KEY (`teacherPreference`)
    REFERENCES `UniViewUsers`.`teData` (`idTeData`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
